kucoin:
  api-key: 60bb766e7bba9b00063c6f24
  api-secret: 4d745e4c-f863-4c0d-bee8-18498b832b43
  api-password: scott123

huobi:
  api-key: dqnh6tvdf3-9d59f51f-ed085d95-e22f6
  secret-key: 81206161-8db8e66b-808990ea-c07c2

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
    url: jdbc:mysql://127.0.0.1:3306/coin?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates

logback:
  level: DEBUG
